// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCC2vCwL_BwhrUhFNVB4oTWErkdSsHBhc4',
    appId: '1:960360954345:web:f9698770c029fd9def7378',
    messagingSenderId: '960360954345',
    projectId: 'technolochat',
    authDomain: 'technolochat.firebaseapp.com',
    storageBucket: 'technolochat.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEy4hlfqECPj4svSZhDpo8b7DqjLBrCE0',
    appId: '1:960360954345:android:795ba491221814c8ef7378',
    messagingSenderId: '960360954345',
    projectId: 'technolochat',
    storageBucket: 'technolochat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoSR43JpP4vQqgejnFDOJTmSySjpyg2Rg',
    appId: '1:960360954345:ios:3b3e62d8a4857d97ef7378',
    messagingSenderId: '960360954345',
    projectId: 'technolochat',
    storageBucket: 'technolochat.appspot.com',
    androidClientId: '960360954345-kk4mkluios3lllkb3v83hdmpi1vlr6oj.apps.googleusercontent.com',
    iosClientId: '960360954345-q0h9ube02a10gfid10o3aconvjmm7fhg.apps.googleusercontent.com',
    iosBundleId: 'com.example.technoloChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoSR43JpP4vQqgejnFDOJTmSySjpyg2Rg',
    appId: '1:960360954345:ios:1fad87aec6a49198ef7378',
    messagingSenderId: '960360954345',
    projectId: 'technolochat',
    storageBucket: 'technolochat.appspot.com',
    androidClientId: '960360954345-kk4mkluios3lllkb3v83hdmpi1vlr6oj.apps.googleusercontent.com',
    iosClientId: '960360954345-s44adm33njjqttaimegi71lbdt2gsj2e.apps.googleusercontent.com',
    iosBundleId: 'com.example.technoloChat.RunnerTests',
  );
}
